# Generated by Django 4.2.30 on 2026-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_userprofile_daily_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(choices=[('free', 'Free Play'), ('random', 'Random Puzzle'), ('daily', 'Daily Challenge'), ('custom', 'Custom Puzzle'), ('practice', 'Practice Mode'), ('story', 'Story Mode')], default='random', max_length=20),
        ),
    ]
